[package]
name = "audio"
version = "0.1.0"
authors = ["Matthew Quinn <matt@mquinn.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
